import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import { Countries } from "@/components/Countries";
import queryClient from "../lib/clients/react-query";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { useQuery } from "react-query";
import { dehydrate } from "react-query/hydration";
import { fetchCountries } from "@/lib/queries/fetch-countries";

const Home: InferGetServerSidePropsType<typeof getServerSideProps> = () => {
  const { data } = useQuery("countries", fetchCountries);
  return (
    <>
      <Head>
        <title>Search and filter countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* TODO: Implement my own icon <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* TODO: Implement Loading */}
      <Flex as={"main"} flexDir={"column"} maxW={"1000px"} m={"0 auto"}>
        {data ? <Countries countries={data} /> : "..."}
      </Flex>
    </>
  );
};

const getServerSideProps: GetServerSideProps = async () => {
  await queryClient.prefetchQuery("countries", fetchCountries);
  return {
    props: {
      dehydrateState: dehydrate(queryClient),
    },
  };
};
export default Home;
